[package]
name = "tpt-elec-spice-noise"
description = "Thermal, shot, and flicker noise source models"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
tpt-elec-core = { workspace = true }
tpt-elec-spice-models = { workspace = true }

[lints]
workspace = true
