[package]
name = "tpt-elec-geometry"
description = "PCB geometry primitives and voxel meshes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
tpt-elec-core = { workspace = true }

[lints]
workspace = true
